import random
import time
from pathlib import Path
from datetime import datetime
from structai import save_file
from tqdm import tqdm

# Academic discipline taxonomy based on UNESCO nomenclature.
# See: https://en.wikipedia.org/wiki/UNESCO_nomenclature

academic_disciplines = {
    "Mathematics": [
        "Algebra",
        "Linear Algebra",
        "Abstract Algebra",
        "Commutative Algebra",
        "Homological Algebra",
        "Representation Theory",
        "Calculus",
        "Real Analysis",
        "Complex Analysis",
        "Functional Analysis",
        "Harmonic Analysis",
        "Non-standard Analysis",
        "Geometry",
        "Euclidean Geometry",
        "Non-Euclidean Geometry",
        "Differential Geometry",
        "Algebraic Geometry",
        "Discrete Geometry",
        "Convex Geometry",
        "Topology",
        "General Topology",
        "Algebraic Topology",
        "Differential Topology",
        "Geometric Topology",
        "Number Theory",
        "Analytic Number Theory",
        "Algebraic Number Theory",
        "Arithmetic Geometry",
        "Logic",
        "Mathematical Logic",
        "Set Theory",
        "Model Theory",
        "Proof Theory",
        "Category Theory",
        "Combinatorics",
        "Enumerative Combinatorics",
        "Extremal Combinatorics",
        "Graph Theory",
        "Ramsey Theory",
        "Probability Theory",
        "Stochastic Processes",
        "Measure Theory",
        "Statistics",
        "Mathematical Statistics",
        "Bayesian Statistics",
        "Computational Statistics",
        "Biostatistics",
        "Differential Equations",
        "Ordinary Differential Equations",
        "Partial Differential Equations",
        "Dynamical Systems",
        "Applied Mathematics",
        "Optimization",
        "Operations Research",
        "Mathematical Cryptography",
        "Control Theory",
        "Mathematical Physics",
        "Game Theory",
        "Information Theory",
        "Numerical Analysis",
        "Scientific Computing"
    ],
    "Physics": [
        "Classical Mechanics",
        "Newtonian Mechanics",
        "Lagrangian Mechanics",
        "Hamiltonian Mechanics",
        "Thermodynamics",
        "Statistical Mechanics",
        "Electromagnetism",
        "Electrodynamics",
        "Quantum Mechanics",
        "Quantum Information",
        "High Energy Physics",
        "Particle Physics",
        "String Theory",
        "Quantum Field Theory",
        "Theoretical Physics",
        "Condensed Matter Physics",
        "Solid State Physics",
        "Soft Matter Physics",
        "Superconductivity",
        "Nanophysics",
        "Astrophysics",
        "Cosmology",
        "Stellar Astrophysics",
        "Galactic Astrophysics",
        "Exoplanetology",
        "Dark Matter Physics",
        "Dark Energy Physics",
        "Nuclear Physics",
        "Atomic Physics",
        "Molecular Physics",
        "Optical Physics",
        "Quantum Optics",
        "Photonics",
        "Plasma Physics",
        "Nuclear Fusion",
        "Biophysics",
        "Geophysics",
        "Fluid Dynamics",
        "Relativity",
        "General Relativity",
        "Special Relativity",
        "Gravitational Physics",
        "Acoustics",
        "Medical Physics"
    ],
    "Chemistry": [
        "Organic Chemistry",
        "Organic Synthesis",
        "Stereochemistry",
        "Organometallic Chemistry",
        "Physical Organic Chemistry",
        "Inorganic Chemistry",
        "Coordination Chemistry",
        "Bioinorganic Chemistry",
        "Solid State Chemistry",
        "Main Group Chemistry",
        "Physical Chemistry",
        "Chemical Thermodynamics",
        "Chemical Kinetics",
        "Quantum Chemistry",
        "Spectroscopy",
        "Analytical Chemistry",
        "Mass Spectrometry",
        "Chromatography",
        "Electroanalysis",
        "Chemical Sensors",
        "Biochemistry",
        "Enzymology",
        "Metabolic Biochemistry",
        "Structural Biochemistry",
        "Theoretical Chemistry",
        "Computational Chemistry",
        "Nuclear Chemistry",
        "Radiochemistry",
        "Polymer Chemistry",
        "Environmental Chemistry",
        "Atmospheric Chemistry",
        "Aquatic Chemistry",
        "Green Chemistry",
        "Medicinal Chemistry",
        "Pharmaceutical Chemistry",
        "Supramolecular Chemistry",
        "Materials Chemistry",
        "Nanomaterials Chemistry",
        "Ceramic Chemistry",
        "Composite Materials Chemistry",
        "Electrochemistry",
        "Photochemistry",
        "Surface Chemistry",
        "Colloid Chemistry"
    ],
    "Life Sciences": [
        "Molecular Biology",
        "Proteomics",
        "Metabolomics",
        "Transcriptomics",
        "Genomics",
        "Cell Biology",
        "Cytology",
        "Organelle Biology",
        "Cell Signaling",
        "Genetics",
        "Human Genetics",
        "Population Genetics",
        "Epigenetics",
        "Cytogenetics",
        "Microbiology",
        "Bacteriology",
        "Virology",
        "Mycology",
        "Parasitology",
        "Immunology",
        "Innate Immunology",
        "Adaptive Immunology",
        "Clinical Immunology",
        "Biochemistry",
        "Biophysics",
        "Structural Biology",
        "Botany",
        "Plant Physiology",
        "Plant Pathology",
        "Plant Systematics",
        "Plant Anatomy",
        "Zoology",
        "Entomology",
        "Ornithology",
        "Herpetology",
        "Ichthyology",
        "Mammalogy",
        "Ecology",
        "Population Ecology",
        "Community Ecology",
        "Ecosystem Ecology",
        "Conservation Biology",
        "Behavioral Ecology",
        "Evolutionary Biology",
        "Phylogenetics",
        "Bioinformatics",
        "Computational Biology",
        "Neuroscience",
        "Cellular Neuroscience",
        "Systems Neuroscience",
        "Cognitive Neuroscience",
        "Computational Neuroscience",
        "Developmental Biology",
        "Embryology",
        "Stem Cell Biology",
        "Physiology",
        "Human Physiology",
        "Comparative Physiology",
        "Exercise Physiology",
        "Marine Biology",
        "Biological Oceanography",
        "Systems Biology",
        "Biotechnology",
        "Synthetic Biology"
    ],
    "Computer Science": [
        "Algorithms",
        "Data Structures",
        "Software Engineering",
        "Requirements Engineering",
        "Software Design",
        "Software Testing",
        "Software Maintenance",
        "Database Systems",
        "Information Retrieval",
        "Computer Networks",
        "Network Protocols",
        "Wireless Networks",
        "Internet of Things",
        "Software Defined Networking",
        "Cybersecurity",
        "Cryptography",
        "Network Security",
        "Information Privacy",
        "Operating Systems",
        "Virtualization",
        "Computer Architecture",
        "Hardware Engineering",
        "Human Computer Interaction",
        "User Experience Design",
        "Computer Graphics",
        "Data Visualization",
        "Augmented Reality",
        "Virtual Reality",
        "Distributed Systems",
        "Cloud Computing",
        "Edge Computing",
        "Programming Languages",
        "Compilers",
        "Theory of Computation",
        "Computational Complexity Theory",
        "Automata Theory",
        "Computability Theory",
        "Quantum Computing",
        "Embedded Systems",
        "Real Time Systems",
        "Formal Methods",
        "Computational Bioinformatics"
    ],
    "Artificial Intelligence": [
        "Machine Learning",
        "Supervised Learning",
        "Unsupervised Learning",
        "Deep Learning",
        "Neural Networks",
        "Natural Language Processing",
        "Large Language Models",
        "Speech Processing",
        "Computer Vision",
        "Image Processing",
        "Video Analysis",
        "Robotics",
        "Robot Perception",
        "Robot Control",
        "Robot Planning",
        "Human Robot Interaction",
        "Reinforcement Learning",
        "Expert Systems",
        "Rule Based Systems",
        "Generative AI",
        "Knowledge Representation",
        "Automated Reasoning",
        "Ontologies",
        "Automated Planning",
        "Scheduling",
        "Multi Agent Systems",
        "Game Theory AI",
        "AI Ethics",
        "AI Safety",
        "AI Alignment",
        "Explainable AI",
        "Evolutionary Computation",
        "Swarm Intelligence",
        "Neural Symbolic AI"
    ],
    "Economics": [
        "Microeconomics",
        "Macroeconomics",
        "Econometrics",
        "Quantitative Economics",
        "Development Economics",
        "Behavioral Economics",
        "Experimental Economics",
        "Game Theory Economics",
        "Mechanism Design",
        "Labor Economics",
        "International Economics",
        "International Trade",
        "International Finance",
        "Financial Economics",
        "Asset Pricing",
        "Corporate Finance",
        "Public Economics",
        "Public Finance",
        "Industrial Organization",
        "History of Economic Thought",
        "Environmental Economics",
        "Resource Economics",
        "Health Economics",
        "Urban Economics",
        "Regional Economics",
        "Political Economy"
    ],
    "Medicine & Healthcare": [
        "Internal Medicine",
        "General Internal Medicine",
        "Nephrology",
        "Pulmonology",
        "Rheumatology",
        "Infectious Diseases",
        "Surgery",
        "General Surgery",
        "Cardiothoracic Surgery",
        "Neurosurgery",
        "Orthopedic Surgery",
        "Plastic Surgery",
        "Transplant Surgery",
        "Pediatrics",
        "General Pediatrics",
        "Neonatology",
        "Cardiology",
        "Interventional Cardiology",
        "Electrophysiology",
        "Neurology",
        "Oncology",
        "Medical Oncology",
        "Surgical Oncology",
        "Radiation Oncology",
        "Psychiatry",
        "Addiction Psychiatry",
        "Child and Adolescent Psychiatry",
        "Forensic Psychiatry",
        "Radiology",
        "Nuclear Medicine",
        "Anesthesiology",
        "Pain Medicine",
        "Pathology",
        "Anatomic Pathology",
        "Clinical Pathology",
        "Forensic Pathology",
        "Dermatology",
        "Emergency Medicine",
        "Critical Care Medicine",
        "Pharmacology",
        "Toxicology",
        "Epidemiology",
        "Public Health",
        "Geriatrics",
        "Palliative Care",
        "Obstetrics",
        "Gynecology",
        "Maternal Fetal Medicine",
        "Reproductive Endocrinology",
        "Orthopedics",
        "Sports Medicine",
        "Ophthalmology",
        "Gastroenterology",
        "Hepatology",
        "Endocrinology",
        "Diabetes",
        "Metabolism",
        "Otolaryngology",
        "Rehabilitation Medicine",
        "Dentistry",
        "Oral Sciences",
        "Nursing Science",
        "Nutrition",
        "Dietetics"
    ],
    "Earth & Space Sciences": [
        "Geology",
        "Structural Geology",
        "Tectonics",
        "Sedimentology",
        "Stratigraphy",
        "Geophysics",
        "Seismology",
        "Geodynamics",
        "Geomagnetism",
        "Meteorology",
        "Atmospheric Science",
        "Weather Forecasting",
        "Climate Dynamics",
        "Oceanography",
        "Physical Oceanography",
        "Chemical Oceanography",
        "Biological Oceanography",
        "Geological Oceanography",
        "Paleontology",
        "Vertebrate Paleontology",
        "Invertebrate Paleontology",
        "Paleobotany",
        "Hydrology",
        "Water Resources",
        "Volcanology",
        "Geochemistry",
        "Petrology",
        "Environmental Science",
        "Environmental Pollution",
        "Sustainability Science",
        "Soil Science",
        "Pedology",
        "Edaphology",
        "Glaciology",
        "Cryosphere Science",
        "Planetary Science",
        "Planetary Geology",
        "Planetary Atmospheres",
        "Climatology",
        "Paleoclimatology",
        "Geodesy",
        "Surveying",
        "Mineralogy",
        "Crystallography"
    ],
    "Engineering": [
        "Civil Engineering",
        "Structural Engineering",
        "Geotechnical Engineering",
        "Transportation Engineering",
        "Hydraulic Engineering",
        "Construction Engineering",
        "Mechanical Engineering",
        "Engineering Thermodynamics",
        "Fluid Mechanics",
        "Solid Mechanics",
        "Manufacturing Engineering",
        "Electrical Engineering",
        "Power Engineering",
        "Electronics Engineering",
        "Control Systems Engineering",
        "Signal Processing",
        "Telecommunications Engineering",
        "Chemical Engineering",
        "Process Engineering",
        "Chemical Reaction Engineering",
        "Transport Phenomena",
        "Separation Processes",
        "Aerospace Engineering",
        "Aerodynamics",
        "Aerospace Propulsion",
        "Flight Dynamics",
        "Avionics",
        "Biomedical Engineering",
        "Biomechanics",
        "Biomaterials",
        "Medical Devices",
        "Tissue Engineering",
        "Industrial Engineering",
        "Systems Engineering",
        "Operations Research Engineering",
        "Human Factors Engineering",
        "Supply Chain Engineering",
        "Materials Science",
        "Metallurgy",
        "Ceramics Engineering",
        "Polymer Engineering",
        "Composite Materials",
        "Semiconductor Engineering",
        "Nuclear Engineering",
        "Nuclear Fission Engineering",
        "Nuclear Fusion Engineering",
        "Radiation Protection",
        "Environmental Engineering",
        "Water Treatment",
        "Wastewater Treatment",
        "Air Quality Engineering",
        "Waste Management",
        "Petroleum Engineering",
        "Mining Engineering",
        "Robotics Engineering",
        "Mechatronics",
        "Computer Engineering",
        "Computer Hardware Engineering",
        "Embedded Systems Engineering",
        "VLSI Design",
        "Agricultural Engineering",
        "Biological Engineering",
        "Ocean Engineering",
        "Marine Engineering",
        "Nanotechnology",
        "Nanoengineering"
    ]
}

RESEARCH_TYPES = [
    "Theory",
    "Experiment",
    "Application",
    "Methodology",
    "Simulation",
    "Data Analysis",
    "Tool"
]

GRANULARITY_LEVELS = [
    "Microscopic",
    "Macroscopic",
    "Mesoscopic",
    "System Level",
    "Component Level"
]


def generate_random_config(subject_name=None, num_keywords=3):
    """
    Generate a random experiment configuration for a given academic discipline.

    Args:
        subject_name (str, optional): Name of the academic discipline. If None,
                                      a random discipline is chosen.
        num_keywords (int): Number of keywords to randomly select (default: 3).

    Returns:
        dict: Configuration dict with keys: field, keywords, research_type,
              granularity_level.

    Raises:
        ValueError: If ``subject_name`` is not found in ``academic_disciplines``.
    """
    if subject_name is None:
        subject_name = random.choice(list(academic_disciplines.keys()))

    if subject_name not in academic_disciplines:
        raise ValueError(f"Subject '{subject_name}' not found in academic_disciplines.")

    available_keywords = academic_disciplines[subject_name]

    # Cap the sample size to the number of available keywords
    k = min(num_keywords, len(available_keywords))
    selected_keywords = random.sample(available_keywords, k)

    config = {
        "field": subject_name,
        "keywords": selected_keywords,
        "research_type": random.choice(RESEARCH_TYPES),
        "granularity_level": random.choice(GRANULARITY_LEVELS)
    }

    return config


if __name__ == "__main__":
    BASE_DIR = Path(__file__).resolve().parent
    for _ in range(5):
        for subject_name in tqdm(academic_disciplines):
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"{timestamp}.json"
            output_path = BASE_DIR / filename
            config = generate_random_config(subject_name=subject_name, num_keywords=5)
            save_file(config, str(output_path))
            time.sleep(1)
